apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  labels:
    label-key1: label-value1
  annotations:
    annotation-key1: annotation-value
    annotation-key2: veri long annotation value, bla bla bla bla bla bla
spec:
  containers:
    - name: container-name
      image: image-name
      ports:
        - containerPort: 80
      livenessProbe: #ini pengecekan klo terjadi kesalahan service akan di restart
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 0 # pengecekan pertama mau berapa detik setelah containernya hidup (ini defaultnya 0 jadi klo ga di set )
        periodSeconds: 10 # seberapa sering? (ini berarti 10 detik sekali)
        timeoutSeconds: 1 # kalo response lebih dari 1 detik maka dianggap ga sehat
        successThreshold: 1 # setalah ga sehat, mau dianggap sehat setelah berapa kali pengecekan?
        failureThreshold: 3 # berapakali pengecekan sampe dianggap ga sehat
      readinessProbe: # ini pengecekan klo ada masalah dengan aplikasi maka traffic ke aplikasi akan dihentikan
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      startupProbe:
        httpGet:
          path: / 
          port: 80
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3